updating documentation for new formatting of element attributes
redhat-developer/vscode-xml pull request #636
Opened 2022-01-18 18:27 UTC by twoseascharlie

client side documentation update for:
redhat-developer/vscode-xml#633

this PR is dependent on the server side PR:
eclipse/lemminx#1151

2022-01-18 18:28 UTC, twoseascharlie commented
@angelozerr Can you take a look and let me know what you think please?

2022-01-19 22:38 UTC, twoseascharlie commented
I've updated my commits with my gpg signature, sorry for the noise

2022-01-24 11:12 UTC, fbricon requested changes
Couple minor nitpicks, but looks good overall

2022-01-24 11:12 UTC, fbricon commented on docs/Symbols.md
> +* `expressions` (required) : defines a list of expression. An expression is composed of:
list of expressions

2022-01-24 11:12 UTC, fbricon commented on docs/Symbols.md
> +  *  `excluded` (optional): true if the node which matches the xpath must be excluded or not. By default the excluded is set to false.
By default, `excluded` is set to false.

2022-01-24 15:17 UTC, twoseascharlie commented on docs/Symbols.md
> +  *  `excluded` (optional): true if the node which matches the xpath must be excluded or not. By default the excluded is set to false.
updated

2022-01-24 15:18 UTC, twoseascharlie commented on docs/Symbols.md
> +* `expressions` (required) : defines a list of expression. An expression is composed of:
updated

2022-01-24 19:46 UTC, angelozerr commented
LGTM @fbricon if you are OK you can merge it.

2022-01-24 22:07 UTC, fbricon approved these changes

2022-01-24 22:08 UTC, merged

2022-01-24 22:08 UTC, fbricon commented
thanks @twoseascharlie!