Changelog for 0.24.0
redhat-developer/vscode-xml pull request #867
Opened 2023-01-27 20:30 UTC by rgrunber

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

2023-01-27 21:08 UTC, datho7561 requested changes

2023-01-27 21:08 UTC, datho7561 commented on CHANGELOG.md
> + * Support identation for XML contributed languages. See [#862](https://github.com/redhat-developer/vscode-xml/pull/862).
identation --> indentation

2023-01-27 21:08 UTC, datho7561 commented on CHANGELOG.md
> + * Update documentation with document link for `xi:include/@href`. See [#846](https://github.com/redhat-developer/vscode-xml/pull/846).
I don't think these are worthwhile listing in the changelog, since most of these are documentation for features listed in the features section.

2023-01-31 09:31 UTC, merged

2023-01-31 09:31 UTC, angelozerr commented
Thanks @rgrunber !

2023-02-01 15:56 UTC, angelozerr commented
@oscarlevin please note vscode-xml 0.24.0 is released, you could be interested with:

 * https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLReferencesFeatures.md
 * https://github.com/eclipse/lemminx/pull/1429#issuecomment-1381821185
 * https://github.com/eclipse/lemminx/pull/1455#issuecomment-1404665475